### ISSUE TITLE
Create program to merge ODK data with OSM

### ISSUE THREAD

**Issue by robsavoye** [hotosm/odkconvert#7]
When using an external dataset with ODK Collect that contains existing OSM data, the existing tags need to be conflated with the tags from ODK Collect. This would be after the ODK data is converted to OSM format. Often the existing OSM data may have a few tags already, but ODK is adding more values, so they need to be merged.

**Comment by robsavoye** [comment]
This program is relatively easy, and would reuse most of the code from the building conflator program. The file handling is the same, the only difference is that instead of checking for a duplicate building, it merges tags/values together from ODK and OSM. As the same OSM ID is used for the merged feature, and it's marked as a modified feature, these can be searched for in JOSM for quick validation and uploading to OSM. This will be necessary if using select_from_file with external datasets of OSM features.

**Comment by ivangayton** [comment]
I think this is a high-priority item for communities doing large-scale field mapping. Please let me know if there's anything I can do to help, whether that be example datasets or whatever.

**Comment by robsavoye** [comment]
Just to be clear, this is a separate project from ODK to OSM data conversion. That already works. This is to extend that to support when using existing OSM data in ODK/Kobo Collect, and conflating it with existing OSM data after ODK has added or changed. This is just merging tags/values, not converting them. This program would assume any data has already been converted by odkconvert before conflation.

**Comment by ivangayton** [comment]
Yes, understood. It's very important for communities doing large-scale field mapping, because ensuring that data previously entered into OSM prior to field mapping doesn't get overwritten or damaged is critical, currently requires a lot of work, and is error-prone.

**Comment by robsavoye** [comment]
Having had to do this manually last week, I'm starting on this program as we'll want to use it in Jan.

**Comment by robsavoye** [comment]
This now works with #763e821. It requires a small change to the database scheme we're using for raw data, just adding a column for the refs of a way.  This program generates an OSM XML file for JOSM. Once this is loaded into JOSM, do *update modified*, and/or download OSM data. Then manually validate the data and upload.
