### ISSUE TITLE
Move readme to wiki home & symlink

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/odkconvert#81]
To save content duplication I think we should move the README content to docs/Homepage.md.

Then we should create a symlink for the README, so the homepage file is used as both the README and wiki landing page.

`ln -s README.md docs/Homepage.md`

**Comment by mohammadareeb95** [comment]
I think that's a good idea, can I take this?

**Comment by spwoodcock** [comment]
Yes of course 👍

**Comment by spwoodcock** [comment]
Closed by
